{"name": "test_getdebug", "status": "broken", "statusDetails": {"message": "TypeError: read_very_eager() got an unexpected keyword argument 'timeout'", "trace": "self = <test_onu.Test_Check1 object at 0x00000219127CE9D0>\n\n    def test_getdebug(self):\n        name = self.getfilename()\n        a = 1\n        j = 3\n        list=[\"gcImage_0408.bin\",\"gcImage_530.bin\"]\n        list1=[\"V01.02.00\",\"V01.00.00\"]\n        for i in range (1,1000):\n            name1 = \"round%s\"%i\n>           self.p2.tel_debug()\n\ntest_onu.py:195: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_onu.Test_Check object at 0x00000219127CE400>\n\n    def tel_debug(self):\n        self.tn = telnetlib.Telnet(self.ip,self.port,timeout=10)\n        self.tn.read_until(b\"login: \",timeout=1)\n        self.tn.write(str(\"user\").encode('ascii')+b\"\\n\")\n        self.tn.read_until(b'Passward: ',timeout=1)\n        self.tn.write(str(\"user123\").encode('ascii')+b'\\n')\n        self.tn.read_until(b\"# \",timeout=1)\n        self.tn.write(str(\"su\").encode('ascii')+b\"\\n\")\n        self.tn.read_until(b'Passward: ',timeout=1)\n        self.tn.write(str(\"gala@123\").encode('ascii')+b'\\n')\n>       rel = self.tn.read_very_eager(timeout=30).decode('utf-8')\nE       TypeError: read_very_eager() got an unexpected keyword argument 'timeout'\n\nlogin.py:54: TypeError"}, "start": 1686047943814, "stop": 1686047945911, "uuid": "66d62495-bad2-4067-b096-be0d597ac217", "historyId": "3816510b449309509eadca6aef118664", "testCaseId": "3816510b449309509eadca6aef118664", "fullName": "test_onu.Test_Check1#test_getdebug", "labels": [{"name": "suite", "value": "test_onu"}, {"name": "subSuite", "value": "Test_Check1"}, {"name": "host", "value": "l29707B"}, {"name": "thread", "value": "13984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_onu"}]}